modLoader="javafml"
loaderVersion="[27,)"
[[mods]]
    modId="experiments"
    version="EXPERIMENTAL"
    displayName="Experiments"
    description='''Just my experiments with Forge'''
[[dependencies.experiments]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.experiments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"